### PR TITLE
Add OGX360 support from netham45

### PR DESCRIPTION
**Pull request by jackrayner**
Takes the hard work from https://github.com/netham45/blueretro and integrates it into master on the upstream BlueRetro repository.

### CODE REVIEW

**Comment by darthcloud** [comment]
The build fail on the CI can you look into it?

Also I see warning for the ogx code that will need to be fixed too.

@netham45 or @jackrayner not sure which one of you can handle that.

Also some docs will need to be created in https://github.com/darthcloud/BlueRetroWiki (you can open a PR in that repo)

I don't mind merging it, but I will not test it myself each new release. I will likely send you a head up a couple weeks before with a beta build to test.

I will assign the bug related to that to you guys and also ping you in the discussion forum when I see discussion about this.

If that fine with you then once the error/warning are fixed we xan merge this.

**Comment by jackrayner** [comment]
> The build fail on the CI can you look into it?
> 
> Also I see warning for the ogx code that will need to be fixed too.
> 
> @netham45 or @jackrayner not sure which one of you can handle that.
> 
> Also some docs will need to be created in https://github.com/darthcloud/BlueRetroWiki (you can open a PR in that repo)
> 
> I don't mind merging it, but I will not test it myself each new release. I will likely send you a head up a couple weeks before with a beta build to test.
> 
> I will assign the bug related to that to you guys and also ping you in the discussion forum when I see discussion about this.
> 
> If that fine with you then once the error/warning are fixed we xan merge this.

Hey @darthcloud ,

Apologies, I'd intended to make a PR on my fork! I haven't performed any testing as of yet, but it would be great if/when I validate this is working to get it merged into BlueRetro. 

For now, would the best thing be to close this PR and I can reopen one once I'm happy with it?

**Comment by darthcloud** [comment]
Ok no worries @jackrayner, feel to resubmit when it's ready!

**Comment by ntippie** [comment]
@jackrayner Just wanted to add that I am hopeful to have this added. Cheering you on! 🎊

**Comment by rdmrocha** [comment]
@jackrayner I'm also looking into this and maybe we can share learnings. I'm still finding issues with PS3 and PS5 controllers and would love to brainstorm with you

**Comment by konwektor** [comment]
@rdmrocha I fight with PS3, PS4 support already a long, long time. On some Blueretro versions get better or worse, also depends is it hw1, or hw2 compilation . Got some suspects, and ideas how (maybe) possible to solve it, but mine coding skills are quite weak, and I am looking for ppl with skills and will to help . Contact me , to talk about Yours issiues if You still want to share experience.
@jackrayner I have tried to contact with You over yours gmail adress from github info.(fake maybe?), and also left comment and propose of improvement  code at your fork. If You Still in this project,  - pls contact me.

**Comment by technopal** [comment]
I followed this guide: https://youtu.be/r4PG4MqMDyg

**Pull request closed without merging**
